### ISSUE TITLE
Case Study Revision: jkitzes

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#101]
@jkitzes 
Thanks for still requesting an issue.  I’ll prune this down just to the things that _are_ relevant to you, and hence should be revised, so please check out the points below.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please provide a little more description of your case study project, in your answer to question 1 in the introduction.

Narrative
- [x] Consider adding a link to the final publication that you mention at the beginning of your Narrative: “The final analysis was published in PLoS ONE (doi:10.1371/journal.pone.0096341)”
- [x] Can you provide more background and information about BatID, since this is unique to your case study and won’t be explained in the glossary or anywhere else.
- [x] Consider adding Key Tools section (although this is optional)
- [x] Please read carefully checking for typos or grammatical errors

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
@fatmai @jkitzes  This one seems to be lagging behind, have we heard anything from him?

**Comment by jkitzes** [comment]
He says he needs a 6 month extension, would that be ok? :-D

Should be able to finish this up either Weds or Fri this week.

**Comment by fatmai** [comment]
👍

**Comment by danielturek** [comment]
Merged #112 and closing.
