### ISSUE TITLE
Clean up/format case studies

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#124]
@jkitzes: The formatted versions of the case studies are now in the submissions_cleaned branch. 

fyi, in all case studies, I moved the question

(2) Define what the term "reproducibility" means to you generally and/or in the particular context of your case study. 

from the Introduction to the end as a new question with the following headline

**Comment by danielturek** [comment]
@fatmai If you're happy with the cleaned and re-organized case studies, shall we open a PR from the submissions_cleaned branch into master?  That would make it easier to review the changes and merge them in.

**Comment by fatmai** [comment]
@danielturek, yes I am happy with the cleaned/re-organized case studies. I think @jkitzes wanted to give us the last go before merging it into master (?)

**Comment by danielturek** [comment]
Great.  I took a brief look, and the changes in your submissions_cleaned branch looked good as far as I saw.

**Comment by jkitzes** [comment]
Sounds good - I'll have a look at the branch and then merge it in.

**Comment by danielturek** [comment]
@jkitzes and @fatmai one of you might have to do this same "cleaning" process to the newly revised kram case study.  The revisions have just been merged into submissions branch.

**Comment by fatmai** [comment]
thanks, @danielturek. I can do it tonight.

**Comment by fatmai** [comment]
@jkitzes, @danielturek: the newly revised kram case study is now under the submissions_cleaned branch.

**Comment by danielturek** [comment]
Thanks @fatmai

**Comment by danielturek** [comment]
`submissions_cleaned` branch was merged into `submissions` on 16 May 2016.
