### ISSUE TITLE
choldgraf Minor case study revision

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#127]
@choldgraf Can you please add a short description of PEP8 and PEP257 checkers to your case study, for those who are unfamiliar?

Please make sure to submit changes to the `submissions` branch.

Thanks!

**Comment by choldgraf** [comment]
yep, will do this soon.

**Comment by danielturek** [comment]
This has been resolved Chris, no action needed from you.

**Comment by danielturek** [comment]
Merged #129, closing.
