### ISSUE TITLE
kasmislan Minor case study revison

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#128]
@kallisons Can you please make one minor change (addition) to your case study?  Can you elaborate slightly, with just a few sentences in the "Pain Points" section, where the text currently reads:

Archiving my code takes additional time.

Thank you!

**Comment by kallisons** [comment]
I will add some text.  When do you need the revision?

**Comment by danielturek** [comment]
I'm sorry to ask so soon, but would it be possible by Friday?  This can be a very quick addition, nothing extensive is necessary.  Thanks.

**Comment by kallisons** [comment]
Text has been added to the "Pain Points" section.  Let me know if you need additional text.

**Comment by danielturek** [comment]
@kallisons Can you please pull from the submissions branch of BIDS/repro-case-studies, then make the changes once again to kasmislan.md (there have been a lot of formatting changes since), then open a PR from this updated file, into the submissions branch?  Thank you.  I'm going to close the current PR.

**Comment by jkitzes** [comment]
Text moved over in 85ee5ab9be14b5ee134b9506edb076a86f05e189.

**Comment by danielturek** [comment]
Thanks for the manual merge @jkitzes
