### ISSUE TITLE
barbera: Minor change in your case study

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#133]
Hi @pablobarbera, we got further revisions back and one question came up regarding the following sentence in your case study:

"This is information that most users are not aware could not be inferred based only on their public personal information, which raises the question of whether the concept of informed consent in sharing users' data  -- as defined in the Terms of Service that users accept when they sign up for a Twitter account -- applies in this context as well."

Did you mean "could be inferred", instead of "could not be inferred"?

I can make the change in your case study once you confirm either way. Thanks!

**Comment by pablobarbera** [comment]
Yes, it should be "could be inferred." Thanks!

**Comment by fatmai** [comment]
great, thanks for the quick response. I changed it.
