### ISSUE TITLE
gchristensen: Minor revisions for your case study

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#134]
Hi @garretchristensen, we got some revisions back and there are a few minor points that I would like you to go over: 
- [ ] Could you please revise the following sentence. It is difficult to read it:
  "I obtained this data from a public Defense Department website, and though I still have, and have archived on Dataverse, the dataset I downloaded and used, perhaps unsurprisingly, the original website is no longer operable."
- [ ] Is the last paragraph of your case study perhaps better under Pain Points. It is the pargraph that starts with:
  "I’d say that my code is fairly well-documented. Reading through it, I hope that
  other researchers could understand what the code is doing. [...]"

**Comment by fatmai** [comment]
hi @garretchristensen, any chance you can look over these minor revisions today?

**Comment by garretchristensen** [comment]
Did a PR in the fatma_edits branch.

Garret

On Mon, Jul 11, 2016 at 1:57 PM, fatmai notifications@github.com wrote:

> hi @garretchristensen https://github.com/garretchristensen, any chance
> you can look over these minor revisions today?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BIDS/repro-case-studies/issues/134#issuecomment-231813350,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHcsArIR1H0cIBoZ1uqwyP4RR3kil9y5ks5qUoQZgaJpZM4JGhZC
> .

## 

Garret Christensen, PhD
Assistant Project Scientist, Berkeley Initiative for Transparency in the
Social Sciences http://bitss.org
Data Science Fellow, Berkeley Institute for Data Science
http://bids.berkeley.edu

**Comment by fatmai** [comment]
thanks, @garretchristensen. PR #134 looks great. closing issue.
