### ISSUE TITLE
akrause: author introduction to a first person form

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#148]
@andykrause

In order to have a standard voice throughout the author introductions in the book we made the following change in 3e3807b27fa671517b6d1d4f713b8e4c7e360f7e

Could you please briefly review this?

Also, if you like to have your colleague Hossein Estiri a co-author to the chapter, we can certainly do that too. Then we would change the voice from "I" to "We" in this introductory part. Just let me know.

**Comment by andykrause** [comment]
Yes, i've reviewed that change and it is acceptable.

**Comment by fatmai** [comment]
👍  thanks!
