### ISSUE TITLE
Co-author for Anthony Arendt (aarendt) case study?

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#155]
@aaarendt We received a signed contributor agreement from Christian Kienholz, referencing your case study.

Should be be listed as a co-author on your case study?  Just let me know, and I can add him on.

**Comment by aaarendt** [comment]
@danielturek Yes, Christian Kienholz will be a co-author. I will e-mail a few additional ones shortly. Thanks!

**Comment by danielturek** [comment]
Great.  Can you please also send the contributor agreement along to any additional co-authors, and ask them to complete it?

**Comment by danielturek** [comment]
@aaarendt I'm adding the co-author Christian Kienholz now.  Please send another message with any additional co-authors, when you're ready to.

**Comment by danielturek** [comment]
I believe all co-authors all have been added now.
