### ISSUE TITLE
Contributor agreement from Chris Hartgerink

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#164]
@chartgerink We need the signed contributor agreement from you, to publish your case study on reproducible research.  Please let me know if you see this message, and I'll send information about submitting your agreement.  We need it ASAP.

Can you also give me an email address, where I can reach you?

**Comment by jkitzes** [comment]
@chartgerink , thanks for providing.

**Comment by chartgerink** [comment]
Sorry for missing this, it got flooded in my Github notifications.
