### ISSUE TITLE
references in fatmai

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#167]
@jkitzes: I added two new references (included both bibtex and APA form at the end of the case study) to my own case study. How shall we proceed on updating the references. I know that you did this last time, so let me know what is your preferred way to do this.

also I actually pushed these changes already w/o a PR. I thought I was operating on my fork but wasn't. lmk if that is fine.

**Comment by jkitzes** [comment]
No problem, just updated to the format that should render properly - so all set!

**Comment by fatmai** [comment]
great, thanks @jkitzes!
