### ISSUE TITLE
Werner Krause and Dag Tanneberg case study

### ISSUE THREAD

**Issue by garretchristensen** [BIDS/repro-case-studies#172]
- [x] Is there a public link to the database, or the Shiny app that you've created?

- [x] If there is no suggestion for the last question (Would you recommend any specific websites, training courses, or books for learning more about reproducibility?) then delete entirely.

**Comment by dagtann** [comment]
- The database is not yet publicly accessible. We plan to publish it by the end of the year and could provide you with a public link later.
- The last question has been deleted.

**Comment by dagtann** [comment]
Updated the wrong repo. I am fixing things right now.

**Comment by garretchristensen** [comment]
Great, thanks for the quick response. It's fine if there's no public link, but then could we state that somewhere in the text? Maybe soon after the database is first introduced, state that it will be posted when finished, or something to that effect? I just wouldn't want readers to be confused or search for it if not available.

**Comment by dagtann** [comment]
I'll take care of it.

⁣Sent from BlueMail ​

**Comment by garretchristensen** [comment]
@dagtann My apologies if I deleted the title to your workflow at some point, but I couldn't find one. I created a short YAML header in line with the formatting requirements for the book and used the title "Maintaining a Reproducible Database of Political Competition"
If that's OK with you, then we're good to go. If you prefer something else, could you please issue a pull request with the updated title? Thanks!

**Comment by garretchristensen** [comment]
Also, I made a grayscale version of your diagram to be consistent with all the other diagrams. If you're unhappy with that, feel free to try and improve resolution yourself. I'm going to send all this stuff to Justin Kitzes now for inclusion--he may have some other minor comments.

**Comment by dagtann** [comment]
Thanks! The title should be  **Maintaining a Reproducible Database on political Parties, Elections, and Governments**. Competition is only one aspect to what we do. Other than that we are fine with your edits.

**Comment by garretchristensen** [comment]
Updated title.
