### ISSUE TITLE
Is this project still in process?

### ISSUE THREAD

**Issue by davclark** [BIDS/repro-case-studies#33]
I'm guessing no. I sent something around on Slack with no response. If it _is_ still in progress, I finally have something I'd like to submit.

**Comment by jkitzes** [comment]
Yes it is - we'll be soliciting more case studies soon. But if you have something ready now, a PR to the submissions branch would be very welcome.

**Comment by jkitzes** [comment]
@davclark, as we talked about last month or so, we're still accepting submissions - we'd like to have them all by mid January. Let me know if you're still interested, and feel free to submit a PR at any time.
