### ISSUE TITLE
Case Study revision: khinsen

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#41]
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution relating to ActivePages very much.  The Narrative is extremely well written, but the overall presentation is one level more "abstract" than we're looking for.

Narrative
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your Narrative, following the example case study linked below.
- [ ] Once your Diagram is revised, please update the references in your Narrative to the colored boxes to be consistent your the new black & white Diagram.

Diagram
- [ ] Please re-frame your Diagram in the context of your concrete example (molecular dynamics simulations), to clearly relate to the steps described in your Narrative.
- [ ] Are you able to consolidate your Diagram into a single flowchart diagram (rather than two)?  We realize you're presenting distinct concepts, but this level of abstraction is above what we're looking for.
- [ ] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and/or “Stage III: Data Analysis” as is most appropriate to your case study, following their definitions in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please change any color in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here are more traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by khinsen** [comment]
@danielturek Thanks for your feedback! Unfortunately I don't understand exactly what you are looking for.

I can turn my diagram into a single flowchart using more colors, but the result is rather messy (I tried). Moreover, you also want to me convert the diagram to black & white. I don't see how to combine these requests without reducing the information content in the diagram.

As for the level of concreteness, I would say that my diagram is at the same level as [your example](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf). In fact, the only way I see to make it more concrete is to put the actual names of Python scripts and datasets into the diagram.

**Comment by danielturek** [comment]
@khinsen  thanks for the feedback, and I'm more than happy to iterate with you to reach something we're both happy with.  Let me try to disentangle some of the revisions:

We're moving all diagrams to black & white, so however this is accmoplished, your diagram will have to be changed to remove colors.  Whether you use different shapes boxes (circles, squares, etc), different outlines (solid, dotted, etc), or simply distinguish by the names inside the boxes (as in the example), this is a must.  As noted, a key or legend might come in handy.

For adding concreteness, the confusion (or lack of concreteness) comes from multiple boxes labelled "Pyton script" (same for "computed result" and "plot") which can't otherwise be distinguished in your digram, or using the Narrative since these all have the same name.  If these must be distinct boxes in the Diagram, then could you accompany the boxes with the text which describes the distinctions between them?  Either describing their funcational differences, or with specific script (or result, or plot) names, which can be references from the Narrative and explained there?  Does that make sense?

Regarding a single flowchart versus two.  Again, we understand the _point_ of your case study is somewaht embodied in the presense of two diagrams.  If this simplification cannot be made (or not clearly, or not practically) then so be it.  But if possible, I would certainly be interested to take a look at -- even a rough draft or sketch -- of how it might look if you tried to combine it.  This is open for discussion.

Thanks again for your communications.  Let's keep it up!

**Comment by khinsen** [comment]
@danielturek I submitted my revision in PR #67. I ended up removing the second part of the diagram, which is also much less important for understanding my workflow. I hope that the new labels on the boxes make it clear that each box is a distinct piece of information.

**Comment by danielturek** [comment]
I think this is much more clear.  Thanks for updating the diagram, and the narrative follows it nicely.  PR merged, and closing this issue.  Cheers!
