### ISSUE TITLE
Case Study revision: millmanOttoboniStark

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#42]
Your case study represents a useful and interesting example of reproducibility in applied scientific research.  However, in its current state, both the Narrative and Diagram will require significant revision.  We’d like to receive revised case studies no later than April 8th.

Narrative
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your Narrative, following the example case study linked below.
- [ ] Your Narrative appears to be in outline format.  Please reformat as prose, in the form of complete sentences and paragraphs.
- [ ] Your Narrative includes assignments to individuals (e.g., (J. Millman, P. Stark)).  We don't see how these relate to your case study; unless they are somehow necessary, please remove them.
- [ ] Your Narrative includes time requirements (e.g.,  Time: approximately 4 hours).  We don't see how these relate to your case study; if you decide to keep these, then please explain them clearly in your Narrative.

Diagram
- [ ] Please reformat your Diagram to be horizontally (landscape) oriented. Further, your Diagram should occupy no more than 1/2 of a US letter page.  This will require reorganizing your boxes.
- [ ] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis”, following their definitions in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please change the grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [ ] Please provide both the PDF and editable source file for your Diagram.  For the editable source, please use a graphical flowchart editing tool such as draw.io.

Here are more traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by fatmai** [comment]
@jarrodmillman, @kellieotto, @pbstark: We moved the revision deadlines to April 8th. Please let us know if that is a problem.

**Comment by jarrodmillman** [comment]
@fatmai , @danielturek :  I am about half way through the revision (it is taking a bit longer than expected as I need to write the text (we mostly had bullet points) and I have to redo the diagram).   I have a couple big things on my plate this week and won't have time to finish the revision until next week.  I will submit the new draft by Friday, April 15th.

**Comment by fatmai** [comment]
@jarrodmillman April 15th sounds good!

**Comment by danielturek** [comment]
@jarrodmillman Wanted to check-in on the status of your revisions.  We were aiming for your deadline of 15 April.  Please just let us know where you're at.  Thanks!

**Comment by jarrodmillman** [comment]
@danielturek  We are making progress.  I reviewed the current draft with Philip and Kellie today.  I am busy tomorrow, but I will have time to finalize the draft on Thursday and then incorporate any final comments from Philip and Kellie on Friday.   So we will have the complete revision submitted on 4/22.

**Comment by danielturek** [comment]
Great, thanks @jarrodmillman.  We'll look forward to seeing your revision tomorrow.

**Comment by jarrodmillman** [comment]
@danielturek , the revision is almost finished.  There is one subsection that I need Philip to review.  I will submit the final draft tonight or tomorrow.

If you are interested, we are working on the revision here:
https://github.com/statlab/nsgk

**Comment by danielturek** [comment]
@jarrodmillman Thanks for keeping in touch.  Not a problem.  Just create a PR when you've finished the revision, and make sure to create it into the _submissions_ branch (lots of folks making that mistake).  We'll look forward to seeing the revised version.

**Comment by jarrodmillman** [comment]
Will do.

**Comment by jarrodmillman** [comment]
See #116

**Comment by danielturek** [comment]
Revisions received in #116, closing issue, thanks @jarrodmillman.
