### ISSUE TITLE
Case Study revision: cboettig

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#43]
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution relating to Docker and Open Lab notebooks very much.  We're requesting some revisions for your Narrative, and a re-design of your Diagram to a more standardized presentation.

Introduction:
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your Narrative, following the example case study linked below.
- [x] Please elaborate your project and the general motivation and purpose substantially more.  This should really motivate what your case study is all about.

Narrative:
- [x] Please explain the OpenLab Notebook concept better in the beginning.
- [x] Make sure terms like ruby, jeykll, .Rmd files, knitr, DockerHub, Dockerfile, continuous integration, unit testing, Roxygen, are introduced and described.
- [x] The narrative should be a step by step walk through of your diagram with additional information. This link is currently not very clear. One suggestion would to number the different steps in the narrative as well as diagram (e.g. 1. Explore new ideas in open lab notebook, 2. Create public GitHub repository for project, using an R package layout, etc.)
- [x] Please elaborate the following paragraph starting with “Notebook pages do not load these functions as a single package ….”

Other Sections:

Did you mean to leave the following sections blank? Would be great if you could add your experience, as we really think these sections are very beneficial to the reader.
- [x] Pain Points. Can you add something here? 
- [x] Key Benefits.  It seems you have a lot of benefits you could describe!
- [x] Key Tools.  Likewise, it seems you have a lot of key tools that you could mention.

Diagram:
- [x] Please make all lines straight, or using right angles.
- [x] Please do some alignment within the diagram. e.g. “Infrastructure View” and “Elements View”, and also align the two “Zenodo archive DOI” boxes, etc.
- [x] Please ensure that all lines don't overlap with text.
- [x] Odd hyphenation for “version-ed”.  Please fit this word on a single line.
- [x] Generally tidy, clean up, and make more consistent & presentable, generally following the format of the example Diagram linked below.
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the label “Stage II: Data Processing” to your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  This label should be in Helvetica font, bold, 22pt.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here are more traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent the style (in particular for the Diagram) that we're looking for.

**Comment by danielturek** [comment]
Mutual agreement to remove this case study.

**Comment by danielturek** [comment]
Happily!

**Comment by fatmai** [comment]
Thanks a lot, @cboettig for the revised version. This looks great.

Could you also provide a short title for your case study.

Also, I noticed two sentences Introduction and Narrative that needs quick revision:

**Introduction:**
(too many here's in the following sentence)
"My general approach to an open lab notebook has been described previously [@Gewin2013, @Mascarelli2014], while here I focus on documenting more details of the workflow here."

**Narrative**
(3rd Paragraph in the Automated Workflow section)
 "As the notebook is already organized as a Jekyll repository, just with .Rmd-formatted posts instead of plain markdown, existing tools (see servr, Table 1). can easily execute the R code and format it as a new post in the notebook. "

**Comment by cboettig** [comment]
@fatmai @danielturek Thanks!  Just pushed these changes into the PR (#118).  

Only thing I was unsure about was the labeling of "Stage II: Data Processing" on the diagram. As I attempted to justify in the text, my feeling is that these three stages are all captured within the R code in the .Rmd file in my diagram, and don't really belong in separate boxes for my workflow. (I'm sure we could talk at length about scripting vs formal workflow software and the right resolution for and semantics for capturing workflow provenance, but that seems a bit beyond the scope here :-) )

Thanks again for the detailed feedback, very helpful in doing revisions!  Let me know if there's anything more I can adjust.

**Comment by danielturek** [comment]
That makes sense @cboettig.  Here's what I'll suggest.  Could you add one single label in your diagram, reading:

"Stages 1, 2, 3: Data Input, Processing, Analysis"

which could appear in any of several different places, but essentially referring to (either) the Rmd script, or the entire diagram if you feel that's more appropriate.

This would help make your diagram consistent with the other case studies, and I think this solution most accurately reflects your reproducible workflow.  Does that sound reasonable?

This aside, I think your revisions are complete.

Thanks so much for the quick and excellent revisions!  Very happy to have your case study in the book.

**Comment by cboettig** [comment]
@danielturek good idea!  I've added this annotation to the diagram.  (I've also included the source inkscape SVG as well, feel free to tweak as desired)

**Comment by danielturek** [comment]
Revised figure looks great.  Merged #118 and closing this issue.

Thanks again @cboettig!
