### ISSUE TITLE
Case Study revision: aarendt

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#44]
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution. We're requesting some minor revisions in your Narrative and Diagram.

Narrative:
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your Narrative, following the example case study linked below.
- [x] Make sure that GIS, LiDAP, PostGIS, SQL, PostgreSQL, ArcGIS, SQLAlechmey, are introduced and described with one or two sentences.
- [x] Please add a few sentences for the importance of the choice for Microsoft Azure (or in general clouds) and RDBs. This information could be very useful for someone who wants to use this workflow as an example for a similar problem (e.g. in another domain).
- [x] It’s unclear that detailing the contributions of individuals is necessary or important in your Narrative (e.g., E. Burgess generated the majority of the Python code to build plots…, etc).  We suggest removing this level of individual contribution, unless there is a good reason otherwise.

Diagram:
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] You may need to remove extra details from your Diagram (and put them in the narrative) to be able to achieve the minimum size font.
- [x] Remove all icons from your Diagram.  Replace them with text boxes (“Python”, “MS Azure”, etc).
- [x] Boxes in the middle have outlines / grey boxes slightly overlapping or missing, please adjust these.
- [x] Some labels (e.g., Linux Virtual Machine) are overlapping with boxes, or touching sides of boxes, please adjust slightly.
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study: [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Thanks for working on the revision.  #119 seemed to have merge conflicts in the markdown file.  Can you please correct these, and open a new PR.

Also, the modified diagram looks excellent.

**Comment by jkitzes** [comment]
Anthony emailed me the files also and mentioned that he thought he might have made a mistake with the PR. I'll set up a new one now with his revision.

**Comment by danielturek** [comment]
Merged #121, closing issue.
