### ISSUE TITLE
Case study revision: akrause

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#46]
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution. The narrative and diagram are overall very clear, however, we're requesting some minor revisions.

Introduction
- [ ]  Please elaborate your project and the general motivation and purpose substantially more. This should really motivate what your case study is all about. 

Narrative
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your Narrative, following the example case study linked below.
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] Define acronyms like CBD
- [ ] Briefly describe terms like csv-file, SPSS, IDE
- [ ] Please update paper information if published (“An initial paper reporting the results is currently under review.”) 
- [ ] Ideally, your narrative is a step by step description of your diagram with additional information. Although the diagram is neat, the link to the narrative is sometimes missing. We strongly suggest you to use the same words in the narrative as well as the diagram (e.g. where is codeDir represented in the diagram? Is that information in a user specific config file?) 

Diagram
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the labels “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please change any color/grayscale in your diagram to black & white.  You might still use different shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools. We didn’t understand the use of the half color (or grey) and half white boxes.
- [ ] We suggest you to label the different repositories that you mention in the narrative in your diagram.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by andykrause** [comment]
Introduction
•   Please elaborate your project and the general motivation and purpose substantially more. This should really motivate what your case study is all about.
-   Have added more discussion to the introduction regarding the project’s goals, etc. 
  Narrative
  •   Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail). This can be added at the very beginning of your Narrative, following the example case study linked below.
-   Have added title
  •   Please read carefully checking for typos or grammatical errors
-   Done
  •   Define acronyms like CBD
-   Done
  •   Briefly describe terms like csv-file, SPSS, IDE
-   Done
  •   Please update paper information if published (“An initial paper reporting the results is currently under review.”)
-   The paper remains under review
  •   Ideally, your narrative is a step by step description of your diagram with additional information. Although the diagram is neat, the link to the narrative is sometimes missing. We strongly suggest you to use the same words in the narrative as well as the diagram (e.g. where is codeDir represented in the diagram? Is that information in a user specific config file?)
-   Have added explanation to firm up the link between the two.  
  Diagram
  •   Please make the minimum font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
-   All fonts were size 12, not sure how to change this (do you want them even larger?)
  •   Please add the labels “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in CaseStudies123.png as a guideline. These labels should be in Helvetica font, bold, 22pt.
-   Labels are now in size 22
  •   Please change any color/grayscale in your diagram to black & white. You might still use different shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools. We didn’t understand the use of the half color (or grey) and half white boxes.
-   Have included a grayscale version
  •   We suggest you to label the different repositories that you mention in the narrative in your diagram.
-   Have added repository labels to diagram
  •   Please provide both the PDF and editable source file for your Diagram.
-   PDF is attached.  Github issues does not support the file type for the source file.  Please advise)
  Here is a traditional examples of a case study Narrative and Diagram, which represent both the style and degree of "concreteness" that we're looking for.

[repCaseStudy_gray.pdf](https://github.com/BIDS/repro-case-studies/files/199909/repCaseStudy_gray.pdf)

**Comment by fatmai** [comment]
Thanks, @andykrause for the quick revisions. Is it possible to make a black&white version of your diagram instead of grayscale? Once you are ready, would you mind providing us with an editable source file of your diagram (e.g. an SVG, Scalable Vector Graphics, file or similar)?

**Comment by andykrause** [comment]
See attached for source file and black and white version, i'll email you the .svg as github wont accept it.

[repCaseStudy_b&w.pdf](https://github.com/BIDS/repro-case-studies/files/205410/repCaseStudy_b.w.pdf)

**Comment by danielturek** [comment]
Thanks @andykrause.  I've just removed the gray version of your diagram, and added a PDF version of akrause_edited_bw.svg.

Revisions to your Narrative look good; closing this issue.
