### ISSUE TITLE
Case study revision: arokem

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#47]
Your case study represents a useful and interesting example of reproducibility in neuroimaging, and we value this contribution.  The narrative and diagram are very clear. We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [ ] Please use the word “command line” or “shell prompt”
- [ ] Please resolve [citation needed] in the second question

Narrative
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] Please define the acronym SNR, SDR, API
- [ ] Please briefly describe RAID, unit-testing

Diagram

Nothing to add.

**Comment by arokem** [comment]
Regarding the second comment ("command line" vs. "shell prompt"): what exactly do you mean? Do you mean that I should use one or the other, but not both?

**Comment by arokem** [comment]
Would the explanation of RAID be better in the glossary? I noticed that I was writing a rather long (two sentence explanation) that didn't really fit in here.

**Comment by arokem** [comment]
https://github.com/BIDS/repro-case-private/pull/57/commits/c16354d4c8f99074bb9414f7c315d4d4768af535

**Comment by arokem** [comment]
Unit testing is also explained in the glossary. Do you still want me to explain it here as well?

**Comment by arokem** [comment]
Should the glossary explain API in more detail?

**Comment by arokem** [comment]
https://github.com/BIDS/repro-case-private/pull/57/commits/32cc280f1fdda4c6720250c486d939bfe3366232

**Comment by arokem** [comment]
https://github.com/BIDS/repro-case-studies/pull/81

**Comment by fatmai** [comment]
@arokem: yes, I think you should use one or the other ("command line" or "shell prompt") in your text.

regarding RAID and other acronyms, it is good to have at least the definition (what the letters mean) of the acronym in your case study, and a longer explanation (as you added) in the glossary.

**Comment by arokem** [comment]
OK - I've addressed all the comments, I believe. But let me know if I've missed anything.

**Comment by danielturek** [comment]
@arokem thanks for the quick turnaround, your revisions look very good.

Merged #81, and closing this issue.
