### ISSUE TITLE
Case study revision: benmarwick

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#48]
Your case study represents a useful and interesting example of reproducibility of archeological data analysis, and we value this contribution.  The diagram and narrative are very clear. We’re only requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] Please change  “other people” to scientists / other researchers
- [ ] Please give very brief descriptions for the different licenses (CC0 license, CC-BY license)

Diagram
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by benmarwick** [comment]
Thanks for the helpful feedback. PR #55 hopefully addresses everything.

**Comment by fatmai** [comment]
closing issue. PR #55 merged.
