### ISSUE TITLE
Case study revision: cgorgolewski

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#49]
Your case study represents a useful and interesting example of reproducibility in neuroimaging data analysis, and we value this contribution.  The diagram is very clear. We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] The narrative is a little too short, and is intended to be 500-800 words. We suggest to provide more detail on the following: 
  - [ ] Overall background of your project
  - [ ] A little more detail on NeuroVault in the narrative would be very beneficial for the reader
  - [ ] Which data preprocessing steps were used?
  - [ ] Which data fitting method were used?
  - [ ] Elaborate more on the pain points
  - [ ] Explain each of the key tools more, perhaps a short paragraph for each

Diagram
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Case study was dropped.
