### ISSUE TITLE
Case study revision: chartgerink

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#50]
@chartgerink
Your case study represents a useful and interesting example of reproducibility in applied resaerch using human subjects, and we value this contribution.  We’re requesting some minor revisions throughout.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail).  This can be added at the very beginning of your case study, following the example below.
- [ ] Please provide a little more description of your project in your answer to question 1.

Narrative
- [ ] Reading your case study, it’s unclear to me exactly what this project is about.  Can you add one paragraph to the beginning of your Narrative, describing the overall project, or the types of projects encompassed by this workflow?
- [ ] Please add just a bit to the end of your Narrative, to describing the writing process, and the final steps of your Diagram, and remove the parenthetical statement saying that you’re omitting this.
- [ ] Please read carefully checking for typos or grammatical errors

Diagram
- [ ] It’s not clear what the right sidebar “Version controlled in Github” is doing there.  Either connect it to a box (share results and code in Github?), or simply describe this in your Narrative instead.
- [ ] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please reformat your Diagram to be horizontally (landscape) oriented. Further, your Diagram should occupy no more than 1/2 of a US letter page.  This will require reorganizing your boxes.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by chartgerink** [comment]
Great thanks. Will be sure to make the revisions before April 8.

**Comment by danielturek** [comment]
Merged #84 and closing issue.
