### ISSUE TITLE
Case study revision: choldgraf

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#51]
@choldgraf
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  We’re requesting some minor revisions to your Narrative and Diagram.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [x] Please read carefully checking for typos or grammatical errors
- [x] Break down long paragraphs into shorter ideas (throughout entire Narrative).
- [x] Typo in one place, you refer to “fif” file format.  I assume you meant “fiff” ?
- [x] Briefly introduce “fiff” file format, Pandas, SGE, HDF5, 
- [x] Change “In my field” to “In the field of …”

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x]  Please change the one diagnol line so it doesn’t go under another box.  Maybe add right angle turns?
  Once these changes are all made, please provide us with _both_ the PDF and editable source file.
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Although they’re cute, please remove the jokes from your diagram: the sad face, and the Nobel Prize, and any others.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by choldgraf** [comment]
These are great comments - thanks for the feedback and I'll implement them
soon. What's the deadline you guys are shooting for?

**Comment by fatmai** [comment]
Thanks, Chris. April 15th.

**Comment by choldgraf** [comment]
Ah ok, that's plenty of time to address these comments. I'll post here as I have questions etc

**Comment by danielturek** [comment]
Sounds good, thanks for the quick response!

And I'll start adding the "requested by due date" to the notification
emails, great point, Chris.

**Comment by choldgraf** [comment]
Alternatively we could use milestones w/in github, but maybe that's too much machinery?

**Comment by danielturek** [comment]
Yes, and some people aren't so git savvy.

**Comment by choldgraf** [comment]
sounds good, will keep it in my calendar then :)

**Comment by danielturek** [comment]
Update!  Since we're ahead of the game, and aiming to give people 2 weeks
for revisions, we're moving the (loose) deadline to 8 April.  Please update
your calendar!  Thanks, Chris.

**Comment by choldgraf** [comment]
Hey - cleaning this up a bit right now. I think that you recommended a diagram-creation tool that was hosted online somewhere. Do you remember the name of it? I think that my draft of the diagram is hosted there...otherwise I'll have to start from scratch.

**Comment by danielturek** [comment]
draw.io

You certainly may have used it to create your diagram; but unless you still have the original source file somewhere local (or frequently in Google Drive, since it plays nicely with draw.io), then you'd have to start from scratch -- just meaning you'll need to find your original source file.

**Comment by choldgraf** [comment]
sweet - yep, it was draw.io but I think that my old version got lost
somewhere, so I recreated it and it's now in the PR

**Comment by danielturek** [comment]
@choldgraf, your edits in #88 look very good throughout.  Thanks for the timely revisions.  #88 has been merged.

Can you please create one more PR, with the source file for your diagram?  Thanks.

**Comment by fatmai** [comment]
diagram SVG file added in #92. Closing issue.
