### ISSUE TITLE
Case study revision: gchristensen

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#56]
@garretchristensen
Your case study represents a useful and interesting example of reproducibility in social science research, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [x] Typo, should read: “Defense Manpower Data Center” in the introductory questions.
- [x] Could you please remove most of the parenthetical statements from your Narrative?  They can either be changed to regular text if they’re important, or removed if not.
- [x] Please read carefully checking for typos or grammatical errors
- [x] Please describe acronym DCVS
- [x] We suggest that you do some rearrangements, e.g., you could move  the parts about your concern with the quality of the raw data to the Pain Points section.  

Diagram
- [x] Text overlapping with sides of some boxes.  Please make all text fit within boxes.
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please reformat your Diagram to be horizontally (landscape) oriented. Further, your Diagram should occupy no more than 1/2 of a US letter page.  This will require reorganizing your boxes.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by garretchristensen** [comment]
Just sent a pull request with my edits.
Made the changes to my 2 docs: gchristensen.md and gchristensen.pdf. The PDF of the diagram shows the hopefully editable link to the draw.io program that I used to draw the diagram. I'll also post it here.
https://drive.google.com/a/berkeley.edu/file/d/0B_tfJAZML93oamdUdmxNLXctQVU/view?usp=sharing

**Comment by fatmai** [comment]
garret, I made a slight chance in the arrangement of the labels in the diagram, can you check if that is ok [here](https://www.draw.io/?state=%7B%22ids%22:%5B%220B_tfJAZML93oamdUdmxNLXctQVU%22%5D,%22action%22:%22open%22,%22userId%22:%22118211866749420874003%22%7D#G0B_tfJAZML93oamdUdmxNLXctQVU)

**Comment by garretchristensen** [comment]
Sure, looks totally fine. I didn't use the stage 1, 2, 3 labels in my original draft, so I didn't really design the diagram with them in mind, and don't really have strong feelings about what we call what in this regard.

**Comment by danielturek** [comment]
Closing this issue after merging PR #73, files supplied from @garretchristensen

**Comment by fatmai** [comment]
@garretchristensen: We just realized that your diagram is in portrait format instead of landscape. 

Is it possible that you revise that anytime soon? Thanks!
- [ ] Please reformat your Diagram to be horizontally (landscape) oriented. Further, your Diagram should occupy no more than 1/2 of a US letter page. This will require reorganizing your boxes.

**Comment by fatmai** [comment]
@garretchristensen will send reorganized (left-to-right figure) on Thursday.

**Comment by fatmai** [comment]
here is the link for the revised figure: https://drive.google.com/a/berkeley.edu/file/d/0B_tfJAZML93oamdUdmxNLXctQVU/view?usp=sharing

**Comment by danielturek** [comment]
Thanks for updaging the diagram @garretchristensen .

Updated files `gchristensen.svg` and `gchristensen.pdf` were added to PR #130.  Closing this issue.
