### ISSUE TITLE
Case study revision: kasmislan

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#60]
@kallisons
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  For your case study, were looking for only one Diagram and one Narrative.  Can you please reformat in this way?  The style and presentation of [kasmislan_researchworkflow.pdf](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/kasmislan_researchworkflow.pdf) is what we’re looking for.  We’re also requesting the addition of a Title, and some minor revisions to your Narrative.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please provide a little more description of your case study in your answer to question 1.

Narrative
- [x] Please combine into **one** Narrative outlining your reproducible workflow.
- [x] Please read carefully checking for typos or grammatical errors.
- [x] Rather than “In this narrative”, please say “In this case study”.
- [x] Please introduce and explain D3 in your narrative.
- [x] Please describe what netCDF fileformat is and which fields

Diagram
- [x] Please combine into **one** Diagram showing your reproducible workflow.  Please follow the style of [kasmislan_researchworkflow.pdf](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/kasmislan_researchworkflow.pdf).
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by kallisons** [comment]
Yes, I can revise my case study by April 8.  Also, the study and the associated code have now been published so I can provide references.

**Comment by danielturek** [comment]
Excellent, thank you very much.  We'll look forward to seeing the revisions by April 8th.

**Comment by danielturek** [comment]
Received #87, but need PR into submissions branch.

**Comment by kallisons** [comment]
I think that I made a pull request for the revisions into the submissions branch, but I am not sure? 

Are the pain points, key benefits, key tools, and  "General questions about reproducibility" going to be included?

**Comment by fatmai** [comment]
yes, I got the PR #95 to the submission branch. Thanks. Closing this issue.
