### ISSUE TITLE
Using AWS CLI to talk to MTurk - 'cannot find path' error message 

### ISSUE THREAD

**Issue by camlabuk** [BIDS/repro-case-studies#62]
I'm having some problems with using Command Line Tools with AWS and MTurk. I have followed these instructions: https://requester.mturk.com/developer/tools/clt and then followed the 'Get Started' instructions - and Command Line finds 'bin' in the AWS folder, but can't run any commands. It simply returns a 'cannot find path' message. We've even made sure we have the exact version of JAVA mentioned in the script (5.0.6). Is there anything you can suggest? We're at a bit of a loss here!

**Comment by fatmai** [comment]
Are you sure you are in the right repository?

**Comment by danielturek** [comment]
Closing since we believe this issue was submitted to the wrong repository.
