### ISSUE TITLE
Case Study Revision: kbarbary

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#64]
@kbarbary
Your case study represents a useful and interesting example of reproducibility in cosmology, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [ ] Please provide a little more description of your case study in your answer to question 1.

Narrative
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] Please remove [NOTE: Consider putting this intro paragraph before the diagram?]
- [ ] Mixed capital letters used for sncosmo, please be consistent (also check the diagram and update if necessary) 

Diagram
- [ ] Please use same capital letter as in the narrative for sncosmo, i.e., SNCosmo
- [ ] Suggestion: Rename “local repository” to “local git repository”
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the label “Stage III: Data Analysis” to your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  This label should be in Helvetica font, bold, 22pt.
- [ ] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by kbarbary** [comment]
I'll try to finish this off by tomorrow! Should I make the figure 6.5 inches wide (affects effective font size if the figure will be scaled)?

**Comment by danielturek** [comment]
The size of the new PNG file looks good.

**Comment by danielturek** [comment]
Revisions look good, merged #86 and closing this issue.  Thanks for making timely revisions @kbarbary.
