### ISSUE TITLE
Case Study Revision: kottoboni

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#66]
@kellieotto
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [x] Please read carefully checking for typos or grammatical errors. (e.g. The premise of the method is to predict the outcome of interest, change in life expectancy, as well as possible using all covariates exceptthe treatment of interest, sodium.)
- [x] Please remove starting date of the project, instead we recommend you to state the amount of the time you needed to conduct the study. Project begin is hard to relate in a book. 
- [x] Please update the manuscript submission information if necessary (e.g. you mention “A manuscript is in preparation” is this still up to date?)
- [x] Please elaborate the following sentence for a better understanding of your case study: “ Then, if the treatment adds any additional predictive information beyond the covariates, the treatment will be associated with the residuals of the model.”
- [x] As you developed some code we would suggest you to elaborate whether you did some unit testing on the code. If yes, this would be valuable information for the reader.

Diagram
- [x] Please make arrow heads a little bit bigger.  They’re tiny!  =)
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by kellieotto** [comment]
Everything should be revised now.  It's no problem here but just so errors don't propagate in the book, my last name is spelled with an "o" instead of "a": Ottoboni.

**Comment by fatmai** [comment]
@kellieotto: sorry for the spelling error Kellie! just changed the issue ;)

**Comment by danielturek** [comment]
Closed after merging PR #79 from @kellieotto.
