### ISSUE TITLE
Case Study Revision: rjleveque

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#68]
@rjleveque
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  It’s extremely well written, and we’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [ ] Please provide a little more description of your case study in your answer to question 1 in the introduction.

Narrative
- [ ] Please read carefully checking for typos or grammatical errors.
- [ ] Please expand UW, FEMA, at least the first time you introduce it.
- [ ] Please explain rsync, when you introduce it.
- [ ] More explanation regarding your choices to use git, but not github, and the rationale behind not version-controlling the datasets might be useful.
- [ ] I feel more comments about the BitBucket decision would be useful.  Why was it used?  Was this an advantage, or a nuissance?  I feel the use of _both_ git and bitbucket should either be listed as a pain point, or a key benefit.

Diagram
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the labels Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [ ] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Moving discussion to here:

@rjleveque thanks for the quick turnaround! I see you've addressed most everything in #68.

I'm going to go ahead and merge #80. Then make two minor edits to the diagram.

(1) Make the text "UW ResearchWorks archive" fit inside its oval

(2) Adding the labels we've suggested. I agree your case study is about computational science, but we'll try to separate the parts having to do with data processing and management, from those about data anlysis and publication.

Please take a look at the updated rjleveque.pdf diagram.

Your comments, approval, or further changes are welcomed.

**Comment by rjleveque** [comment]
The subdivision into Data Processing and Data Analysis still seems odd to me.  Both processing and analysis went into the project report, and then both were re-worked for the journal article and again for the revision, so in a sense the "code development" bubble that appears three times is what should be subdivided into processing and analysis (or perhaps simulation and analysis in our case).  The new diagram makes it look like the processing took place before the journal submission and the analysis afterwards, which just seems confusing for the reader.

Also we did have a Stage I (Data Input) that doesn't really appear on the diagram, in that our simulations needed topography and bathymetry data for the ocean and Crescent City as well as tide gauge data, all of which was downloaded from various public NOAA sites recently revamped under the NCEI umbrella, https://www.ncei.noaa.gov/

I don't know if it's worth trying to add that to the diagram, or how you want to handle the other stages.  I'll give it some more thought...

**Comment by danielturek** [comment]
Your points are well-understood.  To put this in perspective, we're attempting to fit all case studies into this general framework of data input, data processing, data analysis, which explains the attempt to do so with yours.

I certainly welcome any new ideas, and will continue to think about it myself.  Thanks.

**Comment by danielturek** [comment]
Randy, I just noticed a few typos in your Narrative.  Specifically, "probabalistic" and "assessement", both in the first paragraph.  Can you please also run a spell-check over your entire narrative?

What's the status on considering how to use labels in your diagram?

**Comment by danielturek** [comment]
Merged #110, closing revisions issue.  Thanks @rjleveque.
