### ISSUE TITLE
Case Study Revision: rpoldrack

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#69]
@poldrack
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please provide a little more description of your case study in your answer to question 1 in the introduction.

Narrative
- [x] Please read carefully checking for typos or grammatical errors.
- [x] Please explain Connectome Workbench when you first introduce it.
- [x] Can you split the second-to-last paragraph into several, more descriptive paragraphs?  This currently seems to include the bulk of the description of your diagram.
- [x] Please rephrase your pain points and key benefits in paragraph style, rather than bullet points.
- [x] Should the non-reproducible pre-processing step be included as a pain point?

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Text is overlapping with sides of some boxes.  Please make all text fit within boxes.
- [x] Some of the lines should be straight (e.g.,run_everything -> compare VM results, and also in the top-left of digram, and any others).
- [x] Can you tidy the layout of your boxes, somewhat?  It seems more boxes could be “aligned” horizontally or vertically, to improve the visual experience.  (ex. the three right-most boxes, the vetical spacing of the three boxes in the lower-left, the size of the two cylinders, etc.
- [x] Please add the label “Stage III: Data Analysis” to your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Extended your deadline to 1 May, but we'll check-in before then.

**Comment by danielturek** [comment]
Will do his best for revisions by May 9th.

**Comment by poldrack** [comment]
ok, PR with revised text and figure has been submitted

> On Apr 25, 2016, at 6:57 AM, Daniel Turek notifications@github.com wrote:
> 
> Will do his best for revisions by May 9th.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/BIDS/repro-case-studies/issues/69#issuecomment-214338907

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by danielturek** [comment]
Revisions nearly done in PR #123.  Requesting removing greys from the updated diagram.

**Comment by danielturek** [comment]
PR #123 was updated with final touches to figure.  I manually merged the files in, since #123 was into the master branch, not submissions.  So although that PR was being closed, the revisions have been merged into submissions branch.

Thanks @poldrack !  Closing your revisions issue now.
