### ISSUE TITLE
Case Study Revision: slaybaugh

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#70]
@RachelSlaybaugh
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.

Narrative
- [x] Please read carefully checking for typos or grammatical errors.
- [ ] Is a 0-dimensional version of an algorithm actually testable?  It seems to me reduction to this level is usually totally trivial!  Maybe say 1-D version, instead?  (but then, I’m totally not familiar with your field =)
- [x] Please expand acronyms like API
- [x] Please provide a brief description of Doxygen. Why did you decide to use this tool specifically?
- [x] Could you please present the pain points in paragraph format, similar to your key benefits section?
- [x] Near the end you become a bit more casual (“repo”, “lit review”), I’m guessing because you were nearing the end!  Would you mind formalizing this a little, for overall consistancy?  (also just these casual, wordy sentences at the end: “with little test codes lets you play around with stuff you've already got the next time you're investigating a new …”, etc.)
- [x] Can remove key tools section, if you have none.  But I would suggest even mentioning Doxygen here would be safe and smart.

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add (one or more of) the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, as you feel is appropriate.  To be honest, I’m not sure what subset of these is correct, since most of your narrative / diagram doesn’t explain exactly what these algorithms you’re developing are used for (data simulation? data cleaning? data analysis? something else?).  For adding the appropriate labels, please follow the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please reformat your Diagram to be horizontally (landscape) oriented. Further, your Diagram should occupy no more than 1/2 of a US letter page.  This will require reorganizing your boxes.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by rachelslaybaugh** [comment]
I will do this. Is it at all possible to get an extension? If not I'll make
it happen on time...

**Comment by fatmai** [comment]
@rachelslaybaugh we can give you an extension until April 15th. Hope that helps and you can make it to that  date.

**Comment by fatmai** [comment]
Thanks, @rachelslaybaugh. I merged #106. Looking forward to the diagram. fyi, a lot of people have used draw.io for the diagram during the conference (and couldn't remember anymore :)), so your original file maybe there as well.

leaving this issue open until we finalize the diagram.

**Comment by danielturek** [comment]
Revisions completed, merged #107.
