### ISSUE TITLE
Case Study Revision: vstaneva

### ISSUE THREAD

**Issue by danielturek** [BIDS/repro-case-studies#72]
@valentina-s
Your case study represents a useful and interesting example of reproducibility in applied scientific research, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please provide a little more description of your case study in your answer to question 1 in the introduction.

Narrative
- [x] Please read carefully checking for typos or grammatical errors
- [x] Instead of saying “I will describe the workflow of a project I did in grad school”, please introduce and explain what the actual project is!  I’m sure it will be of interest to readers.
- [x] When you say “most of the research time is spent at this stage”, please give some idea of how much time; days? weeks? Months?
- [x] Maybe consider adding the section on Key Benefits (which was optional), to explain how the field of mathematics is generally conducive to reproducible research, and why?

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] You might consider moving additional details (extra text) from the Diagram to the Narrative.
- [x] Please add the labels “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please change any color/grayscale in your diagram to black & white.  You might consider using additional shaped boxes, or various outline styles for boxes (and adding a legend) to denote different types of information or tools.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by valentina-s** [comment]
@danielturek, Thank you for the comments and suggestions. I made the case study description a bit more formal and shrank the diagram. If it is still too big and wordy, I will work on reducing it more. Should it be in the upper half of the page or just half of the space should be used?

**Comment by danielturek** [comment]
@valentina-s, thanks for the edits to your case study.  The narrative looks very good.  We're requesting additional minor edits to your diagram:
- [x] For the labels, please use exactly these labels: “Stage I: Data Input” (if you feel there is a place for this), “Stage II: Data Processing” and “Stage III: Data Analysis”, to indicate the appropriate sections.
- [x] Please remove the stray arrow pointing into the box "Data simulated from assumed model".
- [x] Can you provide an editable .svg file, rather than .xml?

Thanks!

**Comment by fatmai** [comment]
Looks great! Thanks @valentina-s for your work. PR #99 merged. Closing this issue.
