### ISSUE TITLE
Case Study Revision: kram

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#74]
@kram

Your case study represents a useful and interesting example of reproducibility, and we value this contribution.  We’re requesting the addition of a Title, and some minor revisions to your Narrative and Diagram.  We’d like to receive revised case studies no later than April 8th.

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please define “green up”

Narrative
- [x] Please read carefully checking for typos or grammatical errors. There are grammatical errors, sometimes missing words etc. in the current form of the text. 
- [x] Please revise and clarify the following sentence:  “Close collaborators, and unwitting Twitter followers weigh in during this time.”
- [x] Please briefly describe Zenodo, Figshare, Pandoc when you mention these tools in the text.
- [x] Please briefly describe in which context you use the the tools that you mention (e.g. awk, sed, make file). Also, briefly describe these tools.
- [x] Please expand acronyms like DOI, HPC, API
- [x] Please briefly describe what “(git)ignore” means
- [x] Please change “dois” to DOIs in the last sentence of your narrative.
- [x] There is no mention of the following tools in the narrative (but in the Key tools section) “crossref, Mendeley”. Please briefly describe in which step you use these tools.

Diagram
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage I: Data Input”, “Stage II: Data Processing” and “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please adjust the arrows in the diagram such that they are straight (e.g., R -> Data Acquisition Script, and statistical analyses -> data viz, and exploratory queries -> scratch githug). The curved arrows make the diagram look unnecessarily busy.
- [x] Please change “scratch github” to “scratch github repository” for consistency with the narrative.
- [x] Please keep your Diagram horizontally (landscape) oriented, and occupying no more than 1/2 of a US letter page.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by karthik** [comment]
Apologies for the delay, @fatmai I'll have something in today or tomorrow.

**Comment by fatmai** [comment]
great, thanks @karthik.

**Comment by danielturek** [comment]
Thanks @kram, merged #125 with your case study revisions, closing this issue.
