### ISSUE TITLE
Case Study Revision: ycheah

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#76]
@yocheah

Introduction
- [ ] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [ ] Please provide a little more description of your case study in your answer to question 1 in the introduction.

Narrative
- [ ] Please read carefully checking for typos or grammatical errors
- [ ] Please elaborate following “JIRA, an issue tracking system” (i.e., in your diagram you also mention the bug reporting feature that you could mention in your narrative). (Why is a tracking system important?)
- [ ] Similarly, please give further information about code building here: “Jenkins, a build system is also used to automate the code build.” (Why is this necessary, why did you choose Jenkins as the tool?)

Pain Points
- [ ] Is the following sentence a pain-point? "Since this is ongoing work, we are working on encouraging the use of JIRA as part of keeping track of feature requests and use cases. The use of test procedures are also developed to keep track of the procedures needed to test and to build a full test-suite to help keep track of potential issues.” 
  It doesn’t sound like when reading but maybe we are missing something. Please elaborate. 

Diagram
- [ ] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [ ] Please add the labels “Stage I: Data Input” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [ ] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Case study was dropped.
