### ISSUE TITLE
Case Study Revision: zzhang

### ISSUE THREAD

**Issue by fatmai** [BIDS/repro-case-studies#77]
@zhaozhang

Introduction
- [x] Please provide a one sentence “title” for your case study (e.g., “Developing, testing, and deploying efficient MCMC algorithms for hierarchical models using R”, or an equivalent level of detail), at the very beginning of your case study, following the example below.
- [x] Please provide a little more description of SEP library (either here or in the narrative)

Narrative
- [x] Please briefly describe Spark. Why did you decide to use Spark?
- [x] Please briefly describe what FITS images are.
- [x] In the following sentence:  “4. Thread safety, neither the jFITS library nor the SEP library is thread safe” . Please briefly describe what you mean by thread safe.
- [x] We suggest to take the following sentence out. “ I was in charge of the coding, and Kyle, Frank, and Evan provide technical advise.” Please provide full names if you choose to keep it.
- [x] Please briefly describe and elaborate why you choose to use NERSC and EC2 S3. Please describe what these systems are.
- [x] Please describe the acronym JVM

Diagram
- [x] We would suggest making the overall “flow of information” to be more clear in your diagram.  This might involve (1) removing or combining some boxes, or (2) removing some of the arrows, to simplify your diagram, and make the overall workflow more clear.  For example, where does the main flow of information start, and where does it end?
- [x] Please make the _minimum_ font size in your diagram to be 10pt, and more ideally 11pt (space allowing), using Helvetica font (or similar).
- [x] Please add the labels “Stage III: Data Analysis” to indicate the appropriate sections of your Diagram, following the examples in [CaseStudies123.png](https://github.com/BIDS/repro-case-studies/blob/submissions/CaseStudies123.png) as a guideline.  These labels should be in Helvetica font, bold, 22pt.
- [x] Please keep your Diagram to be horizontally (landscape) oriented, buy occupying closer to 1/2 of a US letter page.  This may require reorganizing your boxes, or removing some amount of detail from your diagram.
- [x] Please provide both the PDF and editable source file for your Diagram.

Here is a traditional examples of a case study [Narrative](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.md) and [Diagram](https://github.com/BIDS/repro-case-studies/blob/submissions/case-studies/dturek.pdf), which represent both the style and degree of "concreteness" that we're looking for.

**Comment by danielturek** [comment]
Extended deadline to 12 April.

**Comment by danielturek** [comment]
Thanks @zhaozhang, merged #98 with your revisions.
